server:
  port: 8091
spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgresql
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    datasource: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect